blank_issues_enabled: true
contact_links:
  - name: Ask a question â“
    url: https://github.com/jasontaylordev/orders/discussions/new
    about: Ask a question or request support for using the template